/** Static marketing content ported from xq-car-web (Car XQ landing). */

export const HERO_BG =
  'https://images.unsplash.com/photo-1493238792000-8113da705763?w=1800&q=85'

export const HOTELS = [
  'The Datai Langkawi',
  'Four Seasons Langkawi',
  'The Andaman, a Luxury Collection',
  'The Westin Langkawi Resort & Spa',
  'The Ritz-Carlton, Langkawi',
  'St Regis Langkawi',
  'Pelangi Beach Resort & Spa',
  'Berjaya Langkawi Resort',
  'Meritus Pelangi Beach Resort',
  'Tanjung Rhu Resort',
  'Bon Ton Resort',
  'Temple Tree Resort',
  'Casa Del Mar',
  'Aseania Resort',
  'Pantai Tengah Sea View Hotel',
  'Frangipani Langkawi Resort',
  'Holiday Villa Beach Resort',
  'Adya Hotel Langkawi',
  'AVANI+ Cenang Hotel',
  'Sunset Beach Resort',
  'La Pari-Pari Langkawi',
] as const

export const CITIES = [
  'Pantai Cenang',
  'Pantai Tengah',
  'Kuah Town',
  'Pantai Kok',
  'Tanjung Rhu',
  'Datai Bay',
  'Padang Matsirat',
  'Burau Bay',
  'Telaga Harbour',
  'Langkawi Airport',
  'Kuah Jetty',
  'Pulau Tuba',
] as const

export const PICK_TIMES = [
  '07:00 AM',
  '08:00 AM',
  '09:00 AM',
  '10:00 AM',
  '10:30 AM',
  '11:00 AM',
  '12:00 PM',
  '01:00 PM',
  '02:00 PM',
  '03:00 PM',
  '04:00 PM',
  '04:30 PM',
  '05:00 PM',
  '06:00 PM',
  '07:00 PM',
  '08:00 PM',
] as const

export const BLOG_TIPS = [
  {
    id: 'ten-tips-driving-langkawi',
    tag: 'Tips',
    title: '10 essential tips for driving in Langkawi',
    excerpt:
      'From left-hand-drive etiquette to navigating Pantai Cenang on a Friday evening — the basics every tourist needs.',
    img: 'https://images.unsplash.com/photo-1502920514313-52581002a659?w=1600&q=85',
  },
  {
    id: 'book-rental-step-by-step',
    tag: 'Guides',
    title: 'How to book your Car XQ rental online — step by step',
    excerpt: 'A quick visual walkthrough of every screen, so your first rental feels like your tenth.',
    img: 'https://images.unsplash.com/photo-1449965408869-eaa3f487e32f?w=1600&q=85',
  },
  {
    id: 'monsoon-travel-langkawi',
    tag: 'Seasonal',
    title: 'Why monsoon season is the quietest time to explore',
    excerpt: 'Fewer crowds, greener hills, and off-peak rates — what to expect if you visit between May and June.',
    img: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1600&q=85',
  },
] as const

export const ATTR_CATS = ['All', 'Beaches', 'Adventure', 'Nature', 'Landmarks'] as const

export const ATTRACTIONS = [
  {
    n: '01',
    t: 'Langkawi Sky Bridge',
    c: 'Adventure',
    d: 'Curved 125m suspension bridge with panoramic island and Andaman Sea views.',
    airport: '20 km',
    jetty: '27 km',
    time: '40 min drive',
    img: 'https://images.unsplash.com/photo-1542448308-5cd00b95da6e?w=1400&q=85',
  },
  {
    n: '02',
    t: 'Langkawi Cable Car (SkyCab)',
    c: 'Adventure',
    d: 'Thrilling ride up to the peak of Gunung Mat Cincang.',
    airport: '19 km',
    jetty: '26 km',
    time: '38 min drive',
    img: 'https://images.unsplash.com/photo-1605649461784-d6f5b5dca8e7?w=900&q=80',
  },
  {
    n: '03',
    t: 'Pantai Cenang',
    c: 'Beaches',
    d: 'Lively beach with white sand, water sports, and nightlife.',
    airport: '7 km',
    jetty: '20 km',
    time: '14 min drive',
    img: 'https://images.unsplash.com/photo-1559554498-bc0fe9b97f56?w=900&q=80',
  },
  {
    n: '04',
    t: 'Kilim Geoforest Park',
    c: 'Nature',
    d: 'UNESCO-recognized mangrove park, sea caves and diverse wildlife.',
    airport: '25 km',
    jetty: '8 km',
    time: '50 min drive',
    img: 'https://images.unsplash.com/photo-1502630859934-b3b41d18206c?w=900&q=80',
  },
  {
    n: '05',
    t: 'Tanjung Rhu Beach',
    c: 'Beaches',
    d: 'Serene beach with clear waters and a tranquil atmosphere.',
    airport: '25 km',
    jetty: '22 km',
    time: '45 min drive',
    img: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80',
  },
  {
    n: '06',
    t: 'Underwater World Langkawi',
    c: 'Landmarks',
    d: "One of Malaysia's largest aquariums.",
    airport: '7 km',
    jetty: '20 km',
    time: '14 min drive',
    img: 'https://images.unsplash.com/photo-1582967788606-a171c1080cb0?w=900&q=80',
  },
  {
    n: '07',
    t: 'Eagle Square (Dataran Lang)',
    c: 'Landmarks',
    d: 'Iconic giant eagle sculpture overlooking the bay.',
    airport: '20 km',
    jetty: '3 km',
    time: '35 min drive',
    img: 'https://images.unsplash.com/photo-1599577180589-0a4d1cd9bf45?w=900&q=80',
  },
  {
    n: '08',
    t: 'Telaga Tujuh Waterfalls',
    c: 'Nature',
    d: 'Seven natural pools, perfect for a swim and a picnic.',
    airport: '13 km',
    jetty: '24 km',
    time: '28 min drive',
    img: 'https://images.unsplash.com/photo-1546587348-d12660c30c50?w=900&q=80',
  },
  {
    n: '09',
    t: 'Langkawi Wildlife Park',
    c: 'Nature',
    d: 'Interactive park with hundreds of species.',
    airport: '20 km',
    jetty: '10 km',
    time: '32 min drive',
    img: 'https://images.unsplash.com/photo-1474314243412-cd4a79f02c6a?w=900&q=80',
  },
  {
    n: '10',
    t: 'Pulau Payar Marine Park',
    c: 'Beaches',
    d: 'Coral reefs and snorkeling — boat transfer from Kuah Jetty.',
    airport: '32 km',
    jetty: 'boat',
    time: '45 min ferry',
    img: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=900&q=80',
  },
] as const

export const FAQS = [
  {
    c: 'Eligibility',
    q: 'What are the requirements to rent a car?',
    a: "If you're between 23 and 65 with a valid Malaysian or International Driving License and at least one year of driving experience, you're good to go.",
  },
  {
    c: 'Pickup & Extras',
    q: 'Can I drive the rental anywhere on the island?',
    a: "Yes. Our cars are perfect for exploring Langkawi from coast to coast. Driving off the island isn't allowed.",
  },
  {
    c: 'Booking & Pricing',
    q: 'How are rental rates calculated?',
    a: 'Rates are set per 24 hours, with discounts for weekly or monthly rentals. Prices vary by season and car type — feel free to ask for the latest.',
  },
  {
    c: 'Insurance & Safety',
    q: 'Is insurance included?',
    a: 'Yes — every rental includes Third-Party Liability Insurance, and you can add extra coverage for additional peace of mind.',
  },
  {
    c: 'Pickup & Extras',
    q: 'Can I pick up my rental right at the airport?',
    a: 'Yes. Let us know your flight and we can arrange meet-and-greet at Langkawi International Airport — Door 3, outside Arrivals.',
  },
  {
    c: 'Insurance & Safety',
    q: 'What happens if I have a breakdown?',
    a: 'Call our 24-hour roadside line and help will be on the way. We typically reach you within 30 minutes anywhere on Langkawi.',
  },
  {
    c: 'Eligibility',
    q: 'Can I add another driver?',
    a: "Of course. Just let us know — there's a small additional driver fee, and they must meet the same age and license requirements.",
  },
  {
    c: 'Booking & Pricing',
    q: 'Can I rent for just a few hours?',
    a: "Our minimum rental is one day, but reach out if you need flexibility — we'll do our best to accommodate.",
  },
  {
    c: 'Booking & Pricing',
    q: 'How do I change or cancel my booking?',
    a: 'Contact our support team. Cancellations made more than 48 hours before pickup are free; later cancellations may have a small fee.',
  },
  {
    c: 'Pickup & Extras',
    q: 'Is Langkawi family-friendly? Do you offer child seats?',
    a: 'Very much so — and yes, we have child seats available on request for a small daily fee.',
  },
  {
    c: 'Insurance & Safety',
    q: "What if I'm running late to return the car?",
    a: "If you're more than 30 minutes late, a small late fee may apply. Just give us a heads-up and we'll work with you.",
  },
  {
    c: 'Eligibility',
    q: 'What documents do I need to bring?',
    a: "Your driver's license, passport, and a credit card for the security deposit — that's it.",
  },
  {
    c: 'Booking & Pricing',
    q: 'Can I rent a car for my whole stay?',
    a: 'Absolutely. We offer flexible weekly and monthly rates so you can explore at your own pace.',
  },
] as const

export const FAQ_CATS = [
  { id: 'All', label: 'All questions' },
  { id: 'Booking & Pricing', label: 'Booking & pricing' },
  { id: 'Eligibility', label: 'Eligibility & drivers' },
  { id: 'Pickup & Extras', label: 'Pickup & extras' },
  { id: 'Insurance & Safety', label: 'Insurance & safety' },
] as const

export const REVIEWS = [
  {
    n: 'Yvonne Koh',
    r: 5,
    role: 'Solo traveller · Kuala Lumpur',
    body: 'Cars were so new and clean — best price I compared across the island. Will definitely choose Car XQ again.',
    date: 'Apr 2026',
    trip: '4-day rental · Perodua Bezza',
  },
  {
    n: 'Angel Lee',
    r: 5,
    role: 'Couples trip · Penang',
    body: 'First time in Langkawi with my partner. Jason and the team handled the car and our activities — total peace of mind.',
    date: 'Mar 2026',
    trip: '3-day rental · Honda City',
  },
  {
    n: 'Gigi Soon',
    r: 5,
    role: 'Family of four · Singapore',
    body: 'Super attentive service. Booked our hotel and car through them and both were spot on.',
    date: 'Feb 2026',
    trip: '6-day rental · Toyota Innova',
  },
  {
    n: 'Mily Keh',
    r: 5,
    role: 'Weekend getaway · Ipoh',
    body: "The car was spotless. Saved me hours of planning — recommended Jason and Bin's service to all my friends.",
    date: 'Jan 2026',
    trip: '3-day rental · Perodua Alza',
  },
  {
    n: 'Jocelyn Teoh',
    r: 5,
    role: 'Friends trip · Kuching',
    body: 'Good service and value. Genuinely hassle-free trip — would recommend to anyone heading to Langkawi.',
    date: 'Dec 2025',
    trip: '5-day rental · Toyota Veloz',
  },
  {
    n: 'Weikei Yap',
    r: 5,
    role: 'Wedding party · Johor Bahru',
    body: 'Even after just renting a car, they suggested island-hopping packages, restaurants, and entrance tickets. Above and beyond.',
    date: 'Nov 2025',
    trip: '7-day rental · Hyundai Staria',
  },
  {
    n: 'Tiffany Tai',
    r: 5,
    role: 'Photographers · Bali',
    body: "Car pickup and drop-off were so convenient. They handled tickets and island hop — we didn't have to do any homework.",
    date: 'Oct 2025',
    trip: '5-day rental · Mini Convertible',
  },
  {
    n: 'Shrek Lim',
    r: 5,
    role: 'Holiday travellers · Bangkok',
    body: 'Good service. Highly recommended for holiday travelers to Langkawi.',
    date: 'Sep 2025',
    trip: '4-day rental · Suzuki Jimny',
  },
] as const

export const REELS = [
  {
    id: 'r1',
    name: 'Yvonne Koh',
    city: 'KL',
    caption: 'Sunrise drive to Pantai Cenang. Stress-free pickup at Door 3.',
    views: '12.4K',
    likes: '1.2K',
    clip: 'https://cdn.coverr.co/videos/coverr-driving-on-an-empty-highway-3041/1080p.mp4',
    thumb: 'https://images.unsplash.com/photo-1502920514313-52581002a659?w=600&q=80',
  },
  {
    id: 'r2',
    name: 'Angel Lee',
    city: 'Penang',
    caption: 'Top of the Sky Bridge with the family. Staria was a gem.',
    views: '8.6K',
    likes: '880',
    clip: 'https://cdn.coverr.co/videos/coverr-driving-through-the-forest-3036/1080p.mp4',
    thumb: 'https://images.unsplash.com/photo-1542448308-5cd00b95da6e?w=600&q=80',
  },
  {
    id: 'r3',
    name: 'Gigi Soon',
    city: 'Singapore',
    caption: 'Veloz fit all our luggage and the dog. Easy island life.',
    views: '23.1K',
    likes: '2.4K',
    clip: 'https://cdn.coverr.co/videos/coverr-driving-on-a-road-1582/1080p.mp4',
    thumb: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=600&q=80',
  },
  {
    id: 'r4',
    name: 'Mily Keh',
    city: 'Ipoh',
    caption: "Tanjung Rhu detour. Calmest beach we've seen this year.",
    views: '5.2K',
    likes: '612',
    clip: 'https://cdn.coverr.co/videos/coverr-driving-down-a-country-road-2632/1080p.mp4',
    thumb: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
  },
  {
    id: 'r5',
    name: 'Weikei Yap',
    city: 'Johor',
    caption: 'Mini convertible at sunset. Worth every ringgit.',
    views: '31.8K',
    likes: '3.1K',
    clip: 'https://cdn.coverr.co/videos/coverr-driving-on-a-coastal-road-2541/1080p.mp4',
    thumb: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=600&q=80',
  },
  {
    id: 'r6',
    name: 'Tiffany Tai',
    city: 'Bali',
    caption: 'Kilim Geoforest morning loop. Booking was 90 seconds, swear.',
    views: '9.4K',
    likes: '1.0K',
    clip: 'https://cdn.coverr.co/videos/coverr-driving-down-the-mountain-3038/1080p.mp4',
    thumb: 'https://images.unsplash.com/photo-1502630859934-b3b41d18206c?w=600&q=80',
  },
] as const
