export const PLAN_SPOTS = [
  { id: 'skybridge', t: 'Langkawi Sky Bridge', cat: 'Adventure', drive: '40 min', desc: 'Curved suspension bridge with island & sea views.' },
  { id: 'cablecar', t: 'Langkawi Cable Car', cat: 'Adventure', drive: '38 min', desc: 'Peak of Gunung Mat Cincang, thrilling ride up.' },
  { id: 'cenang', t: 'Pantai Cenang', cat: 'Beach', drive: '14 min', desc: 'Main beach with water sports & nightlife.' },
  { id: 'kilim', t: 'Kilim Geoforest Park', cat: 'Nature', drive: '50 min', desc: 'UNESCO mangrove, sea caves, monkeys & eagles.' },
  { id: 'rhu', t: 'Tanjung Rhu Beach', cat: 'Beach', drive: '45 min', desc: 'Calm white-sand beach, gentle waters.' },
  { id: 'underwater', t: 'Underwater World Langkawi', cat: 'Landmark', drive: '14 min', desc: 'Large aquarium, great for rainy afternoons.' },
  { id: 'eagle', t: 'Eagle Square (Dataran Lang)', cat: 'Landmark', drive: '35 min', desc: "Iconic giant eagle by Kuah's seafront." },
  { id: 'telaga', t: 'Telaga Tujuh Waterfalls', cat: 'Nature', drive: '28 min', desc: 'Seven natural pools — bring a towel.' },
  { id: 'wildlife', t: 'Langkawi Wildlife Park', cat: 'Nature', drive: '32 min', desc: 'Hundreds of species, interactive exhibits.' },
  { id: 'payar', t: 'Pulau Payar Marine Park', cat: 'Beach', drive: '45 min ferry', desc: 'Snorkel reef trip — boat from Kuah Jetty.' },
  { id: 'datai', t: 'Datai Bay', cat: 'Beach', drive: '55 min', desc: "Hidden bay, one of the world's best beaches." },
  { id: 'burau', t: 'Burau Bay', cat: 'Beach', drive: '30 min', desc: 'Quiet beach near Telaga Harbour Park.' },
  { id: 'perdana', t: 'Perdana Quay (Telaga)', cat: 'Landmark', drive: '32 min', desc: 'Boutique marina, sunset cocktails, regatta hub.' },
  { id: 'nightmarket', t: 'Kuah Night Market', cat: 'Food', drive: '30 min', desc: 'Wednesday night street food market.' },
  { id: 'atma', t: 'Atma Alam Batik Village', cat: 'Culture', drive: '20 min', desc: 'Try painting your own batik with locals.' },
  { id: 'duty-free', t: 'Kuah Duty-Free shops', cat: 'Shopping', drive: '30 min', desc: 'Langkawi is duty-free — pick up gifts on your way back.' },
  { id: 'sunset-cenang', t: 'Pantai Cenang sunset', cat: 'Beach', drive: '14 min', desc: 'Walk-up bars right on the sand at golden hour.' },
] as const
