/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RentalAgreementRouteImport } from './routes/rental-agreement'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PdpaRouteImport } from './routes/pdpa'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as WellKnownUcpRouteImport } from './routes/well-known/ucp'
import { Route as WellKnownOpenidConfigurationRouteImport } from './routes/well-known/openid-configuration'
import { Route as WellKnownOauthProtectedResourceRouteImport } from './routes/well-known/oauth-protected-resource'
import { Route as WellKnownOauthAuthorizationServerRouteImport } from './routes/well-known/oauth-authorization-server'
import { Route as WellKnownApiCatalogRouteImport } from './routes/well-known/api-catalog'
import { Route as WellKnownAcpDotjsonRouteImport } from './routes/well-known/acp[.]json'
import { Route as RCodeRouteImport } from './routes/r/$code'
import { Route as PayRentalIdRouteImport } from './routes/pay/$rentalId'
import { Route as InternalLoginRouteImport } from './routes/internal/login'
import { Route as GuidesPlanDriveRouteImport } from './routes/guides/plan-drive'
import { Route as GuidesPickupReturnRouteImport } from './routes/guides/pickup-return'
import { Route as GuidesPickCarRouteImport } from './routes/guides/pick-car'
import { Route as GuidesKnowHowRouteImport } from './routes/guides/know-how'
import { Route as CheckoutCarIdRouteImport } from './routes/checkout/$carId'
import { Route as BookCarIdRouteImport } from './routes/book/$carId'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AccountRentalsRouteImport } from './routes/account/rentals'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountNotificationsRouteImport } from './routes/account/notifications'
import { Route as LocaleTermsRouteImport } from './routes/$locale/terms'
import { Route as LocaleResetPasswordRouteImport } from './routes/$locale/reset-password'
import { Route as LocaleRentalAgreementRouteImport } from './routes/$locale/rental-agreement'
import { Route as LocaleRegisterRouteImport } from './routes/$locale/register'
import { Route as LocaleRefundPolicyRouteImport } from './routes/$locale/refund-policy'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as LocalePdpaRouteImport } from './routes/$locale/pdpa'
import { Route as LocaleLoginRouteImport } from './routes/$locale/login'
import { Route as LocaleForgotPasswordRouteImport } from './routes/$locale/forgot-password'
import { Route as LocaleAccountRouteImport } from './routes/$locale/account'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as AppRentalsIndexRouteImport } from './routes/app/rentals/index'
import { Route as AppMaintenanceIndexRouteImport } from './routes/app/maintenance/index'
import { Route as AppCustomersIndexRouteImport } from './routes/app/customers/index'
import { Route as ApiV1IndexRouteImport } from './routes/api/v1/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as AdminRentalsIndexRouteImport } from './routes/admin/rentals/index'
import { Route as AdminPromosIndexRouteImport } from './routes/admin/promos/index'
import { Route as AdminMaintenanceIndexRouteImport } from './routes/admin/maintenance/index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AdminCarsIndexRouteImport } from './routes/admin/cars/index'
import { Route as AdminAffiliatesIndexRouteImport } from './routes/admin/affiliates/index'
import { Route as AccountBookingsIndexRouteImport } from './routes/account/bookings/index'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale/blog/index'
import { Route as WellKnownMcpServerCardDotjsonRouteImport } from './routes/well-known/mcp/server-card[.]json'
import { Route as WellKnownAgentSkillsIndexDotjsonRouteImport } from './routes/well-known/agent-skills/index[.]json'
import { Route as InternalInviteTokenRouteImport } from './routes/internal/invite/$token'
import { Route as CheckoutConfirmedRentalIdRouteImport } from './routes/checkout/confirmed/$rentalId'
import { Route as BookingConfirmedRentalIdRouteImport } from './routes/booking/confirmed/$rentalId'
import { Route as AppRentalsRentalIdRouteImport } from './routes/app/rentals/$rentalId'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/app/customers/$customerId'
import { Route as ApiWebhooksIpay88RouteImport } from './routes/api/webhooks/ipay88'
import { Route as ApiPaymentResponseRouteImport } from './routes/api/payment/response'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAcpCheckout_sessionsRouteImport } from './routes/api/acp/checkout_sessions'
import { Route as AdminRentalsRentalIdRouteImport } from './routes/admin/rentals/$rentalId'
import { Route as AdminPromosPromoIdRouteImport } from './routes/admin/promos/$promoId'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin/customers/$customerId'
import { Route as AdminCarsCarIdRouteImport } from './routes/admin/cars/$carId'
import { Route as AdminAffiliatesPayoutsRouteImport } from './routes/admin/affiliates/payouts'
import { Route as AdminAffiliatesAffiliateIdRouteImport } from './routes/admin/affiliates/$affiliateId'
import { Route as AccountBookingsRentalIdRouteImport } from './routes/account/bookings/$rentalId'
import { Route as LocalePayRentalIdRouteImport } from './routes/$locale/pay/$rentalId'
import { Route as LocaleGuidesPlanDriveRouteImport } from './routes/$locale/guides/plan-drive'
import { Route as LocaleGuidesPickupReturnRouteImport } from './routes/$locale/guides/pickup-return'
import { Route as LocaleGuidesPickCarRouteImport } from './routes/$locale/guides/pick-car'
import { Route as LocaleGuidesKnowHowRouteImport } from './routes/$locale/guides/know-how'
import { Route as LocaleCheckoutCarIdRouteImport } from './routes/$locale/checkout/$carId'
import { Route as LocaleBookCarIdRouteImport } from './routes/$locale/book/$carId'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale/blog/$slug'
import { Route as ApiDocumentsInvoiceRentalIdRouteImport } from './routes/api/documents/invoice/$rentalId'
import { Route as ApiDocumentsAgreementRentalIdRouteImport } from './routes/api/documents/agreement/$rentalId'
import { Route as LocaleCheckoutConfirmedRentalIdRouteImport } from './routes/$locale/checkout/confirmed/$rentalId'
import { Route as LocaleBookingConfirmedRentalIdRouteImport } from './routes/$locale/booking/confirmed/$rentalId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalAgreementRoute = RentalAgreementRouteImport.update({
  id: '/rental-agreement',
  path: '/rental-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PdpaRoute = PdpaRouteImport.update({
  id: '/pdpa',
  path: '/pdpa',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const WellKnownUcpRoute = WellKnownUcpRouteImport.update({
  id: '/well-known/ucp',
  path: '/well-known/ucp',
  getParentRoute: () => rootRouteImport,
} as any)
const WellKnownOpenidConfigurationRoute =
  WellKnownOpenidConfigurationRouteImport.update({
    id: '/well-known/openid-configuration',
    path: '/well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const WellKnownOauthProtectedResourceRoute =
  WellKnownOauthProtectedResourceRouteImport.update({
    id: '/well-known/oauth-protected-resource',
    path: '/well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const WellKnownOauthAuthorizationServerRoute =
  WellKnownOauthAuthorizationServerRouteImport.update({
    id: '/well-known/oauth-authorization-server',
    path: '/well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const WellKnownApiCatalogRoute = WellKnownApiCatalogRouteImport.update({
  id: '/well-known/api-catalog',
  path: '/well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const WellKnownAcpDotjsonRoute = WellKnownAcpDotjsonRouteImport.update({
  id: '/well-known/acp.json',
  path: '/well-known/acp.json',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRentalIdRoute = PayRentalIdRouteImport.update({
  id: '/pay/$rentalId',
  path: '/pay/$rentalId',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalLoginRoute = InternalLoginRouteImport.update({
  id: '/internal/login',
  path: '/internal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesPlanDriveRoute = GuidesPlanDriveRouteImport.update({
  id: '/guides/plan-drive',
  path: '/guides/plan-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesPickupReturnRoute = GuidesPickupReturnRouteImport.update({
  id: '/guides/pickup-return',
  path: '/guides/pickup-return',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesPickCarRoute = GuidesPickCarRouteImport.update({
  id: '/guides/pick-car',
  path: '/guides/pick-car',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesKnowHowRoute = GuidesKnowHowRouteImport.update({
  id: '/guides/know-how',
  path: '/guides/know-how',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCarIdRoute = CheckoutCarIdRouteImport.update({
  id: '/checkout/$carId',
  path: '/checkout/$carId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookCarIdRoute = BookCarIdRouteImport.update({
  id: '/book/$carId',
  path: '/book/$carId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRentalsRoute = AccountRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleResetPasswordRoute = LocaleResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleRentalAgreementRoute = LocaleRentalAgreementRouteImport.update({
  id: '/rental-agreement',
  path: '/rental-agreement',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleRegisterRoute = LocaleRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleRefundPolicyRoute = LocaleRefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePdpaRoute = LocalePdpaRouteImport.update({
  id: '/pdpa',
  path: '/pdpa',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleForgotPasswordRoute = LocaleForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAccountRoute = LocaleAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const AppRentalsIndexRoute = AppRentalsIndexRouteImport.update({
  id: '/rentals/',
  path: '/rentals/',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceIndexRoute = AppMaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const ApiV1IndexRoute = ApiV1IndexRouteImport.update({
  id: '/api/v1/',
  path: '/api/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRentalsIndexRoute = AdminRentalsIndexRouteImport.update({
  id: '/rentals/',
  path: '/rentals/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromosIndexRoute = AdminPromosIndexRouteImport.update({
  id: '/promos/',
  path: '/promos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaintenanceIndexRoute = AdminMaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarsIndexRoute = AdminCarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAffiliatesIndexRoute = AdminAffiliatesIndexRouteImport.update({
  id: '/affiliates/',
  path: '/affiliates/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountBookingsIndexRoute = AccountBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AccountRoute,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const WellKnownMcpServerCardDotjsonRoute =
  WellKnownMcpServerCardDotjsonRouteImport.update({
    id: '/well-known/mcp/server-card.json',
    path: '/well-known/mcp/server-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const WellKnownAgentSkillsIndexDotjsonRoute =
  WellKnownAgentSkillsIndexDotjsonRouteImport.update({
    id: '/well-known/agent-skills/index.json',
    path: '/well-known/agent-skills/index.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalInviteTokenRoute = InternalInviteTokenRouteImport.update({
  id: '/internal/invite/$token',
  path: '/internal/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutConfirmedRentalIdRoute =
  CheckoutConfirmedRentalIdRouteImport.update({
    id: '/checkout/confirmed/$rentalId',
    path: '/checkout/confirmed/$rentalId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookingConfirmedRentalIdRoute =
  BookingConfirmedRentalIdRouteImport.update({
    id: '/booking/confirmed/$rentalId',
    path: '/booking/confirmed/$rentalId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppRentalsRentalIdRoute = AppRentalsRentalIdRouteImport.update({
  id: '/rentals/$rentalId',
  path: '/rentals/$rentalId',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksIpay88Route = ApiWebhooksIpay88RouteImport.update({
  id: '/api/webhooks/ipay88',
  path: '/api/webhooks/ipay88',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentResponseRoute = ApiPaymentResponseRouteImport.update({
  id: '/api/payment/response',
  path: '/api/payment/response',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAcpCheckout_sessionsRoute = ApiAcpCheckout_sessionsRouteImport.update({
  id: '/api/acp/checkout_sessions',
  path: '/api/acp/checkout_sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRentalsRentalIdRoute = AdminRentalsRentalIdRouteImport.update({
  id: '/rentals/$rentalId',
  path: '/rentals/$rentalId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromosPromoIdRoute = AdminPromosPromoIdRouteImport.update({
  id: '/promos/$promoId',
  path: '/promos/$promoId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCarsCarIdRoute = AdminCarsCarIdRouteImport.update({
  id: '/cars/$carId',
  path: '/cars/$carId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAffiliatesPayoutsRoute = AdminAffiliatesPayoutsRouteImport.update({
  id: '/affiliates/payouts',
  path: '/affiliates/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAffiliatesAffiliateIdRoute =
  AdminAffiliatesAffiliateIdRouteImport.update({
    id: '/affiliates/$affiliateId',
    path: '/affiliates/$affiliateId',
    getParentRoute: () => AdminRoute,
  } as any)
const AccountBookingsRentalIdRoute = AccountBookingsRentalIdRouteImport.update({
  id: '/bookings/$rentalId',
  path: '/bookings/$rentalId',
  getParentRoute: () => AccountRoute,
} as any)
const LocalePayRentalIdRoute = LocalePayRentalIdRouteImport.update({
  id: '/pay/$rentalId',
  path: '/pay/$rentalId',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleGuidesPlanDriveRoute = LocaleGuidesPlanDriveRouteImport.update({
  id: '/guides/plan-drive',
  path: '/guides/plan-drive',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleGuidesPickupReturnRoute =
  LocaleGuidesPickupReturnRouteImport.update({
    id: '/guides/pickup-return',
    path: '/guides/pickup-return',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleGuidesPickCarRoute = LocaleGuidesPickCarRouteImport.update({
  id: '/guides/pick-car',
  path: '/guides/pick-car',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleGuidesKnowHowRoute = LocaleGuidesKnowHowRouteImport.update({
  id: '/guides/know-how',
  path: '/guides/know-how',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleCheckoutCarIdRoute = LocaleCheckoutCarIdRouteImport.update({
  id: '/checkout/$carId',
  path: '/checkout/$carId',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleBookCarIdRoute = LocaleBookCarIdRouteImport.update({
  id: '/book/$carId',
  path: '/book/$carId',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const ApiDocumentsInvoiceRentalIdRoute =
  ApiDocumentsInvoiceRentalIdRouteImport.update({
    id: '/api/documents/invoice/$rentalId',
    path: '/api/documents/invoice/$rentalId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentsAgreementRentalIdRoute =
  ApiDocumentsAgreementRentalIdRouteImport.update({
    id: '/api/documents/agreement/$rentalId',
    path: '/api/documents/agreement/$rentalId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleCheckoutConfirmedRentalIdRoute =
  LocaleCheckoutConfirmedRentalIdRouteImport.update({
    id: '/checkout/confirmed/$rentalId',
    path: '/checkout/confirmed/$rentalId',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleBookingConfirmedRentalIdRoute =
  LocaleBookingConfirmedRentalIdRouteImport.update({
    id: '/booking/confirmed/$rentalId',
    path: '/booking/confirmed/$rentalId',
    getParentRoute: () => LocaleRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/pdpa': typeof PdpaRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/rental-agreement': typeof RentalAgreementRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/pdpa': typeof LocalePdpaRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/refund-policy': typeof LocaleRefundPolicyRoute
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/rental-agreement': typeof LocaleRentalAgreementRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/rentals': typeof AccountRentalsRoute
  '/api/health': typeof ApiHealthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$carId': typeof BookCarIdRoute
  '/checkout/$carId': typeof CheckoutCarIdRoute
  '/guides/know-how': typeof GuidesKnowHowRoute
  '/guides/pick-car': typeof GuidesPickCarRoute
  '/guides/pickup-return': typeof GuidesPickupReturnRoute
  '/guides/plan-drive': typeof GuidesPlanDriveRoute
  '/internal/login': typeof InternalLoginRoute
  '/pay/$rentalId': typeof PayRentalIdRoute
  '/r/$code': typeof RCodeRoute
  '/well-known/acp.json': typeof WellKnownAcpDotjsonRoute
  '/well-known/api-catalog': typeof WellKnownApiCatalogRoute
  '/well-known/oauth-authorization-server': typeof WellKnownOauthAuthorizationServerRoute
  '/well-known/oauth-protected-resource': typeof WellKnownOauthProtectedResourceRoute
  '/well-known/openid-configuration': typeof WellKnownOpenidConfigurationRoute
  '/well-known/ucp': typeof WellKnownUcpRoute
  '/$locale/': typeof LocaleIndexRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/': typeof ApiIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/book/$carId': typeof LocaleBookCarIdRoute
  '/$locale/checkout/$carId': typeof LocaleCheckoutCarIdRoute
  '/$locale/guides/know-how': typeof LocaleGuidesKnowHowRoute
  '/$locale/guides/pick-car': typeof LocaleGuidesPickCarRoute
  '/$locale/guides/pickup-return': typeof LocaleGuidesPickupReturnRoute
  '/$locale/guides/plan-drive': typeof LocaleGuidesPlanDriveRoute
  '/$locale/pay/$rentalId': typeof LocalePayRentalIdRoute
  '/account/bookings/$rentalId': typeof AccountBookingsRentalIdRoute
  '/admin/affiliates/$affiliateId': typeof AdminAffiliatesAffiliateIdRoute
  '/admin/affiliates/payouts': typeof AdminAffiliatesPayoutsRoute
  '/admin/cars/$carId': typeof AdminCarsCarIdRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/promos/$promoId': typeof AdminPromosPromoIdRoute
  '/admin/rentals/$rentalId': typeof AdminRentalsRentalIdRoute
  '/api/acp/checkout_sessions': typeof ApiAcpCheckout_sessionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/response': typeof ApiPaymentResponseRoute
  '/api/webhooks/ipay88': typeof ApiWebhooksIpay88Route
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/rentals/$rentalId': typeof AppRentalsRentalIdRoute
  '/booking/confirmed/$rentalId': typeof BookingConfirmedRentalIdRoute
  '/checkout/confirmed/$rentalId': typeof CheckoutConfirmedRentalIdRoute
  '/internal/invite/$token': typeof InternalInviteTokenRoute
  '/well-known/agent-skills/index.json': typeof WellKnownAgentSkillsIndexDotjsonRoute
  '/well-known/mcp/server-card.json': typeof WellKnownMcpServerCardDotjsonRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/account/bookings/': typeof AccountBookingsIndexRoute
  '/admin/affiliates/': typeof AdminAffiliatesIndexRoute
  '/admin/cars/': typeof AdminCarsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/maintenance/': typeof AdminMaintenanceIndexRoute
  '/admin/promos/': typeof AdminPromosIndexRoute
  '/admin/rentals/': typeof AdminRentalsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/api/v1/': typeof ApiV1IndexRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/maintenance/': typeof AppMaintenanceIndexRoute
  '/app/rentals/': typeof AppRentalsIndexRoute
  '/$locale/booking/confirmed/$rentalId': typeof LocaleBookingConfirmedRentalIdRoute
  '/$locale/checkout/confirmed/$rentalId': typeof LocaleCheckoutConfirmedRentalIdRoute
  '/api/documents/agreement/$rentalId': typeof ApiDocumentsAgreementRentalIdRoute
  '/api/documents/invoice/$rentalId': typeof ApiDocumentsInvoiceRentalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/pdpa': typeof PdpaRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/rental-agreement': typeof RentalAgreementRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/pdpa': typeof LocalePdpaRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/refund-policy': typeof LocaleRefundPolicyRoute
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/rental-agreement': typeof LocaleRentalAgreementRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/rentals': typeof AccountRentalsRoute
  '/api/health': typeof ApiHealthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$carId': typeof BookCarIdRoute
  '/checkout/$carId': typeof CheckoutCarIdRoute
  '/guides/know-how': typeof GuidesKnowHowRoute
  '/guides/pick-car': typeof GuidesPickCarRoute
  '/guides/pickup-return': typeof GuidesPickupReturnRoute
  '/guides/plan-drive': typeof GuidesPlanDriveRoute
  '/internal/login': typeof InternalLoginRoute
  '/pay/$rentalId': typeof PayRentalIdRoute
  '/r/$code': typeof RCodeRoute
  '/well-known/acp.json': typeof WellKnownAcpDotjsonRoute
  '/well-known/api-catalog': typeof WellKnownApiCatalogRoute
  '/well-known/oauth-authorization-server': typeof WellKnownOauthAuthorizationServerRoute
  '/well-known/oauth-protected-resource': typeof WellKnownOauthProtectedResourceRoute
  '/well-known/openid-configuration': typeof WellKnownOpenidConfigurationRoute
  '/well-known/ucp': typeof WellKnownUcpRoute
  '/$locale': typeof LocaleIndexRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/api': typeof ApiIndexRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/book/$carId': typeof LocaleBookCarIdRoute
  '/$locale/checkout/$carId': typeof LocaleCheckoutCarIdRoute
  '/$locale/guides/know-how': typeof LocaleGuidesKnowHowRoute
  '/$locale/guides/pick-car': typeof LocaleGuidesPickCarRoute
  '/$locale/guides/pickup-return': typeof LocaleGuidesPickupReturnRoute
  '/$locale/guides/plan-drive': typeof LocaleGuidesPlanDriveRoute
  '/$locale/pay/$rentalId': typeof LocalePayRentalIdRoute
  '/account/bookings/$rentalId': typeof AccountBookingsRentalIdRoute
  '/admin/affiliates/$affiliateId': typeof AdminAffiliatesAffiliateIdRoute
  '/admin/affiliates/payouts': typeof AdminAffiliatesPayoutsRoute
  '/admin/cars/$carId': typeof AdminCarsCarIdRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/promos/$promoId': typeof AdminPromosPromoIdRoute
  '/admin/rentals/$rentalId': typeof AdminRentalsRentalIdRoute
  '/api/acp/checkout_sessions': typeof ApiAcpCheckout_sessionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/response': typeof ApiPaymentResponseRoute
  '/api/webhooks/ipay88': typeof ApiWebhooksIpay88Route
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/rentals/$rentalId': typeof AppRentalsRentalIdRoute
  '/booking/confirmed/$rentalId': typeof BookingConfirmedRentalIdRoute
  '/checkout/confirmed/$rentalId': typeof CheckoutConfirmedRentalIdRoute
  '/internal/invite/$token': typeof InternalInviteTokenRoute
  '/well-known/agent-skills/index.json': typeof WellKnownAgentSkillsIndexDotjsonRoute
  '/well-known/mcp/server-card.json': typeof WellKnownMcpServerCardDotjsonRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
  '/account/bookings': typeof AccountBookingsIndexRoute
  '/admin/affiliates': typeof AdminAffiliatesIndexRoute
  '/admin/cars': typeof AdminCarsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/maintenance': typeof AdminMaintenanceIndexRoute
  '/admin/promos': typeof AdminPromosIndexRoute
  '/admin/rentals': typeof AdminRentalsIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/api/v1': typeof ApiV1IndexRoute
  '/app/customers': typeof AppCustomersIndexRoute
  '/app/maintenance': typeof AppMaintenanceIndexRoute
  '/app/rentals': typeof AppRentalsIndexRoute
  '/$locale/booking/confirmed/$rentalId': typeof LocaleBookingConfirmedRentalIdRoute
  '/$locale/checkout/confirmed/$rentalId': typeof LocaleCheckoutConfirmedRentalIdRoute
  '/api/documents/agreement/$rentalId': typeof ApiDocumentsAgreementRentalIdRoute
  '/api/documents/invoice/$rentalId': typeof ApiDocumentsInvoiceRentalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/pdpa': typeof PdpaRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/rental-agreement': typeof RentalAgreementRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/account': typeof LocaleAccountRoute
  '/$locale/forgot-password': typeof LocaleForgotPasswordRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/pdpa': typeof LocalePdpaRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/$locale/refund-policy': typeof LocaleRefundPolicyRoute
  '/$locale/register': typeof LocaleRegisterRoute
  '/$locale/rental-agreement': typeof LocaleRentalAgreementRoute
  '/$locale/reset-password': typeof LocaleResetPasswordRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/rentals': typeof AccountRentalsRoute
  '/api/health': typeof ApiHealthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$carId': typeof BookCarIdRoute
  '/checkout/$carId': typeof CheckoutCarIdRoute
  '/guides/know-how': typeof GuidesKnowHowRoute
  '/guides/pick-car': typeof GuidesPickCarRoute
  '/guides/pickup-return': typeof GuidesPickupReturnRoute
  '/guides/plan-drive': typeof GuidesPlanDriveRoute
  '/internal/login': typeof InternalLoginRoute
  '/pay/$rentalId': typeof PayRentalIdRoute
  '/r/$code': typeof RCodeRoute
  '/well-known/acp.json': typeof WellKnownAcpDotjsonRoute
  '/well-known/api-catalog': typeof WellKnownApiCatalogRoute
  '/well-known/oauth-authorization-server': typeof WellKnownOauthAuthorizationServerRoute
  '/well-known/oauth-protected-resource': typeof WellKnownOauthProtectedResourceRoute
  '/well-known/openid-configuration': typeof WellKnownOpenidConfigurationRoute
  '/well-known/ucp': typeof WellKnownUcpRoute
  '/$locale/': typeof LocaleIndexRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/': typeof ApiIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/book/$carId': typeof LocaleBookCarIdRoute
  '/$locale/checkout/$carId': typeof LocaleCheckoutCarIdRoute
  '/$locale/guides/know-how': typeof LocaleGuidesKnowHowRoute
  '/$locale/guides/pick-car': typeof LocaleGuidesPickCarRoute
  '/$locale/guides/pickup-return': typeof LocaleGuidesPickupReturnRoute
  '/$locale/guides/plan-drive': typeof LocaleGuidesPlanDriveRoute
  '/$locale/pay/$rentalId': typeof LocalePayRentalIdRoute
  '/account/bookings/$rentalId': typeof AccountBookingsRentalIdRoute
  '/admin/affiliates/$affiliateId': typeof AdminAffiliatesAffiliateIdRoute
  '/admin/affiliates/payouts': typeof AdminAffiliatesPayoutsRoute
  '/admin/cars/$carId': typeof AdminCarsCarIdRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/promos/$promoId': typeof AdminPromosPromoIdRoute
  '/admin/rentals/$rentalId': typeof AdminRentalsRentalIdRoute
  '/api/acp/checkout_sessions': typeof ApiAcpCheckout_sessionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/response': typeof ApiPaymentResponseRoute
  '/api/webhooks/ipay88': typeof ApiWebhooksIpay88Route
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/rentals/$rentalId': typeof AppRentalsRentalIdRoute
  '/booking/confirmed/$rentalId': typeof BookingConfirmedRentalIdRoute
  '/checkout/confirmed/$rentalId': typeof CheckoutConfirmedRentalIdRoute
  '/internal/invite/$token': typeof InternalInviteTokenRoute
  '/well-known/agent-skills/index.json': typeof WellKnownAgentSkillsIndexDotjsonRoute
  '/well-known/mcp/server-card.json': typeof WellKnownMcpServerCardDotjsonRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/account/bookings/': typeof AccountBookingsIndexRoute
  '/admin/affiliates/': typeof AdminAffiliatesIndexRoute
  '/admin/cars/': typeof AdminCarsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/maintenance/': typeof AdminMaintenanceIndexRoute
  '/admin/promos/': typeof AdminPromosIndexRoute
  '/admin/rentals/': typeof AdminRentalsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/api/v1/': typeof ApiV1IndexRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/maintenance/': typeof AppMaintenanceIndexRoute
  '/app/rentals/': typeof AppRentalsIndexRoute
  '/$locale/booking/confirmed/$rentalId': typeof LocaleBookingConfirmedRentalIdRoute
  '/$locale/checkout/confirmed/$rentalId': typeof LocaleCheckoutConfirmedRentalIdRoute
  '/api/documents/agreement/$rentalId': typeof ApiDocumentsAgreementRentalIdRoute
  '/api/documents/invoice/$rentalId': typeof ApiDocumentsInvoiceRentalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/about'
    | '/account'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/openapi.json'
    | '/pdpa'
    | '/privacy'
    | '/refund-policy'
    | '/register'
    | '/rental-agreement'
    | '/reset-password'
    | '/terms'
    | '/$locale/about'
    | '/$locale/account'
    | '/$locale/forgot-password'
    | '/$locale/login'
    | '/$locale/pdpa'
    | '/$locale/privacy'
    | '/$locale/refund-policy'
    | '/$locale/register'
    | '/$locale/rental-agreement'
    | '/$locale/reset-password'
    | '/$locale/terms'
    | '/account/notifications'
    | '/account/profile'
    | '/account/rentals'
    | '/api/health'
    | '/blog/$slug'
    | '/book/$carId'
    | '/checkout/$carId'
    | '/guides/know-how'
    | '/guides/pick-car'
    | '/guides/pickup-return'
    | '/guides/plan-drive'
    | '/internal/login'
    | '/pay/$rentalId'
    | '/r/$code'
    | '/well-known/acp.json'
    | '/well-known/api-catalog'
    | '/well-known/oauth-authorization-server'
    | '/well-known/oauth-protected-resource'
    | '/well-known/openid-configuration'
    | '/well-known/ucp'
    | '/$locale/'
    | '/account/'
    | '/admin/'
    | '/api/'
    | '/app/'
    | '/blog/'
    | '/$locale/blog/$slug'
    | '/$locale/book/$carId'
    | '/$locale/checkout/$carId'
    | '/$locale/guides/know-how'
    | '/$locale/guides/pick-car'
    | '/$locale/guides/pickup-return'
    | '/$locale/guides/plan-drive'
    | '/$locale/pay/$rentalId'
    | '/account/bookings/$rentalId'
    | '/admin/affiliates/$affiliateId'
    | '/admin/affiliates/payouts'
    | '/admin/cars/$carId'
    | '/admin/customers/$customerId'
    | '/admin/promos/$promoId'
    | '/admin/rentals/$rentalId'
    | '/api/acp/checkout_sessions'
    | '/api/auth/$'
    | '/api/payment/response'
    | '/api/webhooks/ipay88'
    | '/app/customers/$customerId'
    | '/app/rentals/$rentalId'
    | '/booking/confirmed/$rentalId'
    | '/checkout/confirmed/$rentalId'
    | '/internal/invite/$token'
    | '/well-known/agent-skills/index.json'
    | '/well-known/mcp/server-card.json'
    | '/$locale/blog/'
    | '/account/bookings/'
    | '/admin/affiliates/'
    | '/admin/cars/'
    | '/admin/customers/'
    | '/admin/maintenance/'
    | '/admin/promos/'
    | '/admin/rentals/'
    | '/admin/reports/'
    | '/admin/settings/'
    | '/api/v1/'
    | '/app/customers/'
    | '/app/maintenance/'
    | '/app/rentals/'
    | '/$locale/booking/confirmed/$rentalId'
    | '/$locale/checkout/confirmed/$rentalId'
    | '/api/documents/agreement/$rentalId'
    | '/api/documents/invoice/$rentalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/openapi.json'
    | '/pdpa'
    | '/privacy'
    | '/refund-policy'
    | '/register'
    | '/rental-agreement'
    | '/reset-password'
    | '/terms'
    | '/$locale/about'
    | '/$locale/account'
    | '/$locale/forgot-password'
    | '/$locale/login'
    | '/$locale/pdpa'
    | '/$locale/privacy'
    | '/$locale/refund-policy'
    | '/$locale/register'
    | '/$locale/rental-agreement'
    | '/$locale/reset-password'
    | '/$locale/terms'
    | '/account/notifications'
    | '/account/profile'
    | '/account/rentals'
    | '/api/health'
    | '/blog/$slug'
    | '/book/$carId'
    | '/checkout/$carId'
    | '/guides/know-how'
    | '/guides/pick-car'
    | '/guides/pickup-return'
    | '/guides/plan-drive'
    | '/internal/login'
    | '/pay/$rentalId'
    | '/r/$code'
    | '/well-known/acp.json'
    | '/well-known/api-catalog'
    | '/well-known/oauth-authorization-server'
    | '/well-known/oauth-protected-resource'
    | '/well-known/openid-configuration'
    | '/well-known/ucp'
    | '/$locale'
    | '/account'
    | '/admin'
    | '/api'
    | '/app'
    | '/blog'
    | '/$locale/blog/$slug'
    | '/$locale/book/$carId'
    | '/$locale/checkout/$carId'
    | '/$locale/guides/know-how'
    | '/$locale/guides/pick-car'
    | '/$locale/guides/pickup-return'
    | '/$locale/guides/plan-drive'
    | '/$locale/pay/$rentalId'
    | '/account/bookings/$rentalId'
    | '/admin/affiliates/$affiliateId'
    | '/admin/affiliates/payouts'
    | '/admin/cars/$carId'
    | '/admin/customers/$customerId'
    | '/admin/promos/$promoId'
    | '/admin/rentals/$rentalId'
    | '/api/acp/checkout_sessions'
    | '/api/auth/$'
    | '/api/payment/response'
    | '/api/webhooks/ipay88'
    | '/app/customers/$customerId'
    | '/app/rentals/$rentalId'
    | '/booking/confirmed/$rentalId'
    | '/checkout/confirmed/$rentalId'
    | '/internal/invite/$token'
    | '/well-known/agent-skills/index.json'
    | '/well-known/mcp/server-card.json'
    | '/$locale/blog'
    | '/account/bookings'
    | '/admin/affiliates'
    | '/admin/cars'
    | '/admin/customers'
    | '/admin/maintenance'
    | '/admin/promos'
    | '/admin/rentals'
    | '/admin/reports'
    | '/admin/settings'
    | '/api/v1'
    | '/app/customers'
    | '/app/maintenance'
    | '/app/rentals'
    | '/$locale/booking/confirmed/$rentalId'
    | '/$locale/checkout/confirmed/$rentalId'
    | '/api/documents/agreement/$rentalId'
    | '/api/documents/invoice/$rentalId'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/about'
    | '/account'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/openapi.json'
    | '/pdpa'
    | '/privacy'
    | '/refund-policy'
    | '/register'
    | '/rental-agreement'
    | '/reset-password'
    | '/terms'
    | '/$locale/about'
    | '/$locale/account'
    | '/$locale/forgot-password'
    | '/$locale/login'
    | '/$locale/pdpa'
    | '/$locale/privacy'
    | '/$locale/refund-policy'
    | '/$locale/register'
    | '/$locale/rental-agreement'
    | '/$locale/reset-password'
    | '/$locale/terms'
    | '/account/notifications'
    | '/account/profile'
    | '/account/rentals'
    | '/api/health'
    | '/blog/$slug'
    | '/book/$carId'
    | '/checkout/$carId'
    | '/guides/know-how'
    | '/guides/pick-car'
    | '/guides/pickup-return'
    | '/guides/plan-drive'
    | '/internal/login'
    | '/pay/$rentalId'
    | '/r/$code'
    | '/well-known/acp.json'
    | '/well-known/api-catalog'
    | '/well-known/oauth-authorization-server'
    | '/well-known/oauth-protected-resource'
    | '/well-known/openid-configuration'
    | '/well-known/ucp'
    | '/$locale/'
    | '/account/'
    | '/admin/'
    | '/api/'
    | '/app/'
    | '/blog/'
    | '/$locale/blog/$slug'
    | '/$locale/book/$carId'
    | '/$locale/checkout/$carId'
    | '/$locale/guides/know-how'
    | '/$locale/guides/pick-car'
    | '/$locale/guides/pickup-return'
    | '/$locale/guides/plan-drive'
    | '/$locale/pay/$rentalId'
    | '/account/bookings/$rentalId'
    | '/admin/affiliates/$affiliateId'
    | '/admin/affiliates/payouts'
    | '/admin/cars/$carId'
    | '/admin/customers/$customerId'
    | '/admin/promos/$promoId'
    | '/admin/rentals/$rentalId'
    | '/api/acp/checkout_sessions'
    | '/api/auth/$'
    | '/api/payment/response'
    | '/api/webhooks/ipay88'
    | '/app/customers/$customerId'
    | '/app/rentals/$rentalId'
    | '/booking/confirmed/$rentalId'
    | '/checkout/confirmed/$rentalId'
    | '/internal/invite/$token'
    | '/well-known/agent-skills/index.json'
    | '/well-known/mcp/server-card.json'
    | '/$locale/blog/'
    | '/account/bookings/'
    | '/admin/affiliates/'
    | '/admin/cars/'
    | '/admin/customers/'
    | '/admin/maintenance/'
    | '/admin/promos/'
    | '/admin/rentals/'
    | '/admin/reports/'
    | '/admin/settings/'
    | '/api/v1/'
    | '/app/customers/'
    | '/app/maintenance/'
    | '/app/rentals/'
    | '/$locale/booking/confirmed/$rentalId'
    | '/$locale/checkout/confirmed/$rentalId'
    | '/api/documents/agreement/$rentalId'
    | '/api/documents/invoice/$rentalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  PdpaRoute: typeof PdpaRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RegisterRoute: typeof RegisterRoute
  RentalAgreementRoute: typeof RentalAgreementRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BookCarIdRoute: typeof BookCarIdRoute
  CheckoutCarIdRoute: typeof CheckoutCarIdRoute
  GuidesKnowHowRoute: typeof GuidesKnowHowRoute
  GuidesPickCarRoute: typeof GuidesPickCarRoute
  GuidesPickupReturnRoute: typeof GuidesPickupReturnRoute
  GuidesPlanDriveRoute: typeof GuidesPlanDriveRoute
  InternalLoginRoute: typeof InternalLoginRoute
  PayRentalIdRoute: typeof PayRentalIdRoute
  RCodeRoute: typeof RCodeRoute
  WellKnownAcpDotjsonRoute: typeof WellKnownAcpDotjsonRoute
  WellKnownApiCatalogRoute: typeof WellKnownApiCatalogRoute
  WellKnownOauthAuthorizationServerRoute: typeof WellKnownOauthAuthorizationServerRoute
  WellKnownOauthProtectedResourceRoute: typeof WellKnownOauthProtectedResourceRoute
  WellKnownOpenidConfigurationRoute: typeof WellKnownOpenidConfigurationRoute
  WellKnownUcpRoute: typeof WellKnownUcpRoute
  ApiIndexRoute: typeof ApiIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAcpCheckout_sessionsRoute: typeof ApiAcpCheckout_sessionsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaymentResponseRoute: typeof ApiPaymentResponseRoute
  ApiWebhooksIpay88Route: typeof ApiWebhooksIpay88Route
  BookingConfirmedRentalIdRoute: typeof BookingConfirmedRentalIdRoute
  CheckoutConfirmedRentalIdRoute: typeof CheckoutConfirmedRentalIdRoute
  InternalInviteTokenRoute: typeof InternalInviteTokenRoute
  WellKnownAgentSkillsIndexDotjsonRoute: typeof WellKnownAgentSkillsIndexDotjsonRoute
  WellKnownMcpServerCardDotjsonRoute: typeof WellKnownMcpServerCardDotjsonRoute
  ApiV1IndexRoute: typeof ApiV1IndexRoute
  ApiDocumentsAgreementRentalIdRoute: typeof ApiDocumentsAgreementRentalIdRoute
  ApiDocumentsInvoiceRentalIdRoute: typeof ApiDocumentsInvoiceRentalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental-agreement': {
      id: '/rental-agreement'
      path: '/rental-agreement'
      fullPath: '/rental-agreement'
      preLoaderRoute: typeof RentalAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdpa': {
      id: '/pdpa'
      path: '/pdpa'
      fullPath: '/pdpa'
      preLoaderRoute: typeof PdpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/well-known/ucp': {
      id: '/well-known/ucp'
      path: '/well-known/ucp'
      fullPath: '/well-known/ucp'
      preLoaderRoute: typeof WellKnownUcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/well-known/openid-configuration': {
      id: '/well-known/openid-configuration'
      path: '/well-known/openid-configuration'
      fullPath: '/well-known/openid-configuration'
      preLoaderRoute: typeof WellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/well-known/oauth-protected-resource': {
      id: '/well-known/oauth-protected-resource'
      path: '/well-known/oauth-protected-resource'
      fullPath: '/well-known/oauth-protected-resource'
      preLoaderRoute: typeof WellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/well-known/oauth-authorization-server': {
      id: '/well-known/oauth-authorization-server'
      path: '/well-known/oauth-authorization-server'
      fullPath: '/well-known/oauth-authorization-server'
      preLoaderRoute: typeof WellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/well-known/api-catalog': {
      id: '/well-known/api-catalog'
      path: '/well-known/api-catalog'
      fullPath: '/well-known/api-catalog'
      preLoaderRoute: typeof WellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/well-known/acp.json': {
      id: '/well-known/acp.json'
      path: '/well-known/acp.json'
      fullPath: '/well-known/acp.json'
      preLoaderRoute: typeof WellKnownAcpDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$rentalId': {
      id: '/pay/$rentalId'
      path: '/pay/$rentalId'
      fullPath: '/pay/$rentalId'
      preLoaderRoute: typeof PayRentalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/login': {
      id: '/internal/login'
      path: '/internal/login'
      fullPath: '/internal/login'
      preLoaderRoute: typeof InternalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/plan-drive': {
      id: '/guides/plan-drive'
      path: '/guides/plan-drive'
      fullPath: '/guides/plan-drive'
      preLoaderRoute: typeof GuidesPlanDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/pickup-return': {
      id: '/guides/pickup-return'
      path: '/guides/pickup-return'
      fullPath: '/guides/pickup-return'
      preLoaderRoute: typeof GuidesPickupReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/pick-car': {
      id: '/guides/pick-car'
      path: '/guides/pick-car'
      fullPath: '/guides/pick-car'
      preLoaderRoute: typeof GuidesPickCarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/know-how': {
      id: '/guides/know-how'
      path: '/guides/know-how'
      fullPath: '/guides/know-how'
      preLoaderRoute: typeof GuidesKnowHowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$carId': {
      id: '/checkout/$carId'
      path: '/checkout/$carId'
      fullPath: '/checkout/$carId'
      preLoaderRoute: typeof CheckoutCarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$carId': {
      id: '/book/$carId'
      path: '/book/$carId'
      fullPath: '/book/$carId'
      preLoaderRoute: typeof BookCarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/rentals': {
      id: '/account/rentals'
      path: '/rentals'
      fullPath: '/account/rentals'
      preLoaderRoute: typeof AccountRentalsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/reset-password': {
      id: '/$locale/reset-password'
      path: '/reset-password'
      fullPath: '/$locale/reset-password'
      preLoaderRoute: typeof LocaleResetPasswordRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/rental-agreement': {
      id: '/$locale/rental-agreement'
      path: '/rental-agreement'
      fullPath: '/$locale/rental-agreement'
      preLoaderRoute: typeof LocaleRentalAgreementRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/register': {
      id: '/$locale/register'
      path: '/register'
      fullPath: '/$locale/register'
      preLoaderRoute: typeof LocaleRegisterRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/refund-policy': {
      id: '/$locale/refund-policy'
      path: '/refund-policy'
      fullPath: '/$locale/refund-policy'
      preLoaderRoute: typeof LocaleRefundPolicyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/pdpa': {
      id: '/$locale/pdpa'
      path: '/pdpa'
      fullPath: '/$locale/pdpa'
      preLoaderRoute: typeof LocalePdpaRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/forgot-password': {
      id: '/$locale/forgot-password'
      path: '/forgot-password'
      fullPath: '/$locale/forgot-password'
      preLoaderRoute: typeof LocaleForgotPasswordRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/account': {
      id: '/$locale/account'
      path: '/account'
      fullPath: '/$locale/account'
      preLoaderRoute: typeof LocaleAccountRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/app/rentals/': {
      id: '/app/rentals/'
      path: '/rentals'
      fullPath: '/app/rentals/'
      preLoaderRoute: typeof AppRentalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/maintenance/': {
      id: '/app/maintenance/'
      path: '/maintenance'
      fullPath: '/app/maintenance/'
      preLoaderRoute: typeof AppMaintenanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/': {
      id: '/app/customers/'
      path: '/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/': {
      id: '/api/v1/'
      path: '/api/v1'
      fullPath: '/api/v1/'
      preLoaderRoute: typeof ApiV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rentals/': {
      id: '/admin/rentals/'
      path: '/rentals'
      fullPath: '/admin/rentals/'
      preLoaderRoute: typeof AdminRentalsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promos/': {
      id: '/admin/promos/'
      path: '/promos'
      fullPath: '/admin/promos/'
      preLoaderRoute: typeof AdminPromosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maintenance/': {
      id: '/admin/maintenance/'
      path: '/maintenance'
      fullPath: '/admin/maintenance/'
      preLoaderRoute: typeof AdminMaintenanceIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cars/': {
      id: '/admin/cars/'
      path: '/cars'
      fullPath: '/admin/cars/'
      preLoaderRoute: typeof AdminCarsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/affiliates/': {
      id: '/admin/affiliates/'
      path: '/affiliates'
      fullPath: '/admin/affiliates/'
      preLoaderRoute: typeof AdminAffiliatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/bookings/': {
      id: '/account/bookings/'
      path: '/bookings'
      fullPath: '/account/bookings/'
      preLoaderRoute: typeof AccountBookingsIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/blog'
      fullPath: '/$locale/blog/'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/well-known/mcp/server-card.json': {
      id: '/well-known/mcp/server-card.json'
      path: '/well-known/mcp/server-card.json'
      fullPath: '/well-known/mcp/server-card.json'
      preLoaderRoute: typeof WellKnownMcpServerCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/well-known/agent-skills/index.json': {
      id: '/well-known/agent-skills/index.json'
      path: '/well-known/agent-skills/index.json'
      fullPath: '/well-known/agent-skills/index.json'
      preLoaderRoute: typeof WellKnownAgentSkillsIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/invite/$token': {
      id: '/internal/invite/$token'
      path: '/internal/invite/$token'
      fullPath: '/internal/invite/$token'
      preLoaderRoute: typeof InternalInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/confirmed/$rentalId': {
      id: '/checkout/confirmed/$rentalId'
      path: '/checkout/confirmed/$rentalId'
      fullPath: '/checkout/confirmed/$rentalId'
      preLoaderRoute: typeof CheckoutConfirmedRentalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirmed/$rentalId': {
      id: '/booking/confirmed/$rentalId'
      path: '/booking/confirmed/$rentalId'
      fullPath: '/booking/confirmed/$rentalId'
      preLoaderRoute: typeof BookingConfirmedRentalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rentals/$rentalId': {
      id: '/app/rentals/$rentalId'
      path: '/rentals/$rentalId'
      fullPath: '/app/rentals/$rentalId'
      preLoaderRoute: typeof AppRentalsRentalIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/$customerId': {
      id: '/app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/app/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/ipay88': {
      id: '/api/webhooks/ipay88'
      path: '/api/webhooks/ipay88'
      fullPath: '/api/webhooks/ipay88'
      preLoaderRoute: typeof ApiWebhooksIpay88RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/response': {
      id: '/api/payment/response'
      path: '/api/payment/response'
      fullPath: '/api/payment/response'
      preLoaderRoute: typeof ApiPaymentResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/acp/checkout_sessions': {
      id: '/api/acp/checkout_sessions'
      path: '/api/acp/checkout_sessions'
      fullPath: '/api/acp/checkout_sessions'
      preLoaderRoute: typeof ApiAcpCheckout_sessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rentals/$rentalId': {
      id: '/admin/rentals/$rentalId'
      path: '/rentals/$rentalId'
      fullPath: '/admin/rentals/$rentalId'
      preLoaderRoute: typeof AdminRentalsRentalIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promos/$promoId': {
      id: '/admin/promos/$promoId'
      path: '/promos/$promoId'
      fullPath: '/admin/promos/$promoId'
      preLoaderRoute: typeof AdminPromosPromoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cars/$carId': {
      id: '/admin/cars/$carId'
      path: '/cars/$carId'
      fullPath: '/admin/cars/$carId'
      preLoaderRoute: typeof AdminCarsCarIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/affiliates/payouts': {
      id: '/admin/affiliates/payouts'
      path: '/affiliates/payouts'
      fullPath: '/admin/affiliates/payouts'
      preLoaderRoute: typeof AdminAffiliatesPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/affiliates/$affiliateId': {
      id: '/admin/affiliates/$affiliateId'
      path: '/affiliates/$affiliateId'
      fullPath: '/admin/affiliates/$affiliateId'
      preLoaderRoute: typeof AdminAffiliatesAffiliateIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/bookings/$rentalId': {
      id: '/account/bookings/$rentalId'
      path: '/bookings/$rentalId'
      fullPath: '/account/bookings/$rentalId'
      preLoaderRoute: typeof AccountBookingsRentalIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/$locale/pay/$rentalId': {
      id: '/$locale/pay/$rentalId'
      path: '/pay/$rentalId'
      fullPath: '/$locale/pay/$rentalId'
      preLoaderRoute: typeof LocalePayRentalIdRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/guides/plan-drive': {
      id: '/$locale/guides/plan-drive'
      path: '/guides/plan-drive'
      fullPath: '/$locale/guides/plan-drive'
      preLoaderRoute: typeof LocaleGuidesPlanDriveRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/guides/pickup-return': {
      id: '/$locale/guides/pickup-return'
      path: '/guides/pickup-return'
      fullPath: '/$locale/guides/pickup-return'
      preLoaderRoute: typeof LocaleGuidesPickupReturnRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/guides/pick-car': {
      id: '/$locale/guides/pick-car'
      path: '/guides/pick-car'
      fullPath: '/$locale/guides/pick-car'
      preLoaderRoute: typeof LocaleGuidesPickCarRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/guides/know-how': {
      id: '/$locale/guides/know-how'
      path: '/guides/know-how'
      fullPath: '/$locale/guides/know-how'
      preLoaderRoute: typeof LocaleGuidesKnowHowRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/checkout/$carId': {
      id: '/$locale/checkout/$carId'
      path: '/checkout/$carId'
      fullPath: '/$locale/checkout/$carId'
      preLoaderRoute: typeof LocaleCheckoutCarIdRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/book/$carId': {
      id: '/$locale/book/$carId'
      path: '/book/$carId'
      fullPath: '/$locale/book/$carId'
      preLoaderRoute: typeof LocaleBookCarIdRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/api/documents/invoice/$rentalId': {
      id: '/api/documents/invoice/$rentalId'
      path: '/api/documents/invoice/$rentalId'
      fullPath: '/api/documents/invoice/$rentalId'
      preLoaderRoute: typeof ApiDocumentsInvoiceRentalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/agreement/$rentalId': {
      id: '/api/documents/agreement/$rentalId'
      path: '/api/documents/agreement/$rentalId'
      fullPath: '/api/documents/agreement/$rentalId'
      preLoaderRoute: typeof ApiDocumentsAgreementRentalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/checkout/confirmed/$rentalId': {
      id: '/$locale/checkout/confirmed/$rentalId'
      path: '/checkout/confirmed/$rentalId'
      fullPath: '/$locale/checkout/confirmed/$rentalId'
      preLoaderRoute: typeof LocaleCheckoutConfirmedRentalIdRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/booking/confirmed/$rentalId': {
      id: '/$locale/booking/confirmed/$rentalId'
      path: '/booking/confirmed/$rentalId'
      fullPath: '/$locale/booking/confirmed/$rentalId'
      preLoaderRoute: typeof LocaleBookingConfirmedRentalIdRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleAccountRoute: typeof LocaleAccountRoute
  LocaleForgotPasswordRoute: typeof LocaleForgotPasswordRoute
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocalePdpaRoute: typeof LocalePdpaRoute
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleRefundPolicyRoute: typeof LocaleRefundPolicyRoute
  LocaleRegisterRoute: typeof LocaleRegisterRoute
  LocaleRentalAgreementRoute: typeof LocaleRentalAgreementRoute
  LocaleResetPasswordRoute: typeof LocaleResetPasswordRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleBookCarIdRoute: typeof LocaleBookCarIdRoute
  LocaleCheckoutCarIdRoute: typeof LocaleCheckoutCarIdRoute
  LocaleGuidesKnowHowRoute: typeof LocaleGuidesKnowHowRoute
  LocaleGuidesPickCarRoute: typeof LocaleGuidesPickCarRoute
  LocaleGuidesPickupReturnRoute: typeof LocaleGuidesPickupReturnRoute
  LocaleGuidesPlanDriveRoute: typeof LocaleGuidesPlanDriveRoute
  LocalePayRentalIdRoute: typeof LocalePayRentalIdRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
  LocaleBookingConfirmedRentalIdRoute: typeof LocaleBookingConfirmedRentalIdRoute
  LocaleCheckoutConfirmedRentalIdRoute: typeof LocaleCheckoutConfirmedRentalIdRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleAccountRoute: LocaleAccountRoute,
  LocaleForgotPasswordRoute: LocaleForgotPasswordRoute,
  LocaleLoginRoute: LocaleLoginRoute,
  LocalePdpaRoute: LocalePdpaRoute,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleRefundPolicyRoute: LocaleRefundPolicyRoute,
  LocaleRegisterRoute: LocaleRegisterRoute,
  LocaleRentalAgreementRoute: LocaleRentalAgreementRoute,
  LocaleResetPasswordRoute: LocaleResetPasswordRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleBookCarIdRoute: LocaleBookCarIdRoute,
  LocaleCheckoutCarIdRoute: LocaleCheckoutCarIdRoute,
  LocaleGuidesKnowHowRoute: LocaleGuidesKnowHowRoute,
  LocaleGuidesPickCarRoute: LocaleGuidesPickCarRoute,
  LocaleGuidesPickupReturnRoute: LocaleGuidesPickupReturnRoute,
  LocaleGuidesPlanDriveRoute: LocaleGuidesPlanDriveRoute,
  LocalePayRentalIdRoute: LocalePayRentalIdRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
  LocaleBookingConfirmedRentalIdRoute: LocaleBookingConfirmedRentalIdRoute,
  LocaleCheckoutConfirmedRentalIdRoute: LocaleCheckoutConfirmedRentalIdRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

interface AccountRouteChildren {
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountRentalsRoute: typeof AccountRentalsRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountBookingsRentalIdRoute: typeof AccountBookingsRentalIdRoute
  AccountBookingsIndexRoute: typeof AccountBookingsIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountRentalsRoute: AccountRentalsRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountBookingsRentalIdRoute: AccountBookingsRentalIdRoute,
  AccountBookingsIndexRoute: AccountBookingsIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAffiliatesAffiliateIdRoute: typeof AdminAffiliatesAffiliateIdRoute
  AdminAffiliatesPayoutsRoute: typeof AdminAffiliatesPayoutsRoute
  AdminCarsCarIdRoute: typeof AdminCarsCarIdRoute
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
  AdminPromosPromoIdRoute: typeof AdminPromosPromoIdRoute
  AdminRentalsRentalIdRoute: typeof AdminRentalsRentalIdRoute
  AdminAffiliatesIndexRoute: typeof AdminAffiliatesIndexRoute
  AdminCarsIndexRoute: typeof AdminCarsIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminMaintenanceIndexRoute: typeof AdminMaintenanceIndexRoute
  AdminPromosIndexRoute: typeof AdminPromosIndexRoute
  AdminRentalsIndexRoute: typeof AdminRentalsIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAffiliatesAffiliateIdRoute: AdminAffiliatesAffiliateIdRoute,
  AdminAffiliatesPayoutsRoute: AdminAffiliatesPayoutsRoute,
  AdminCarsCarIdRoute: AdminCarsCarIdRoute,
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
  AdminPromosPromoIdRoute: AdminPromosPromoIdRoute,
  AdminRentalsRentalIdRoute: AdminRentalsRentalIdRoute,
  AdminAffiliatesIndexRoute: AdminAffiliatesIndexRoute,
  AdminCarsIndexRoute: AdminCarsIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminMaintenanceIndexRoute: AdminMaintenanceIndexRoute,
  AdminPromosIndexRoute: AdminPromosIndexRoute,
  AdminRentalsIndexRoute: AdminRentalsIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppRentalsRentalIdRoute: typeof AppRentalsRentalIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppMaintenanceIndexRoute: typeof AppMaintenanceIndexRoute
  AppRentalsIndexRoute: typeof AppRentalsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppRentalsRentalIdRoute: AppRentalsRentalIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppMaintenanceIndexRoute: AppMaintenanceIndexRoute,
  AppRentalsIndexRoute: AppRentalsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  PdpaRoute: PdpaRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RegisterRoute: RegisterRoute,
  RentalAgreementRoute: RentalAgreementRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiHealthRoute: ApiHealthRoute,
  BlogSlugRoute: BlogSlugRoute,
  BookCarIdRoute: BookCarIdRoute,
  CheckoutCarIdRoute: CheckoutCarIdRoute,
  GuidesKnowHowRoute: GuidesKnowHowRoute,
  GuidesPickCarRoute: GuidesPickCarRoute,
  GuidesPickupReturnRoute: GuidesPickupReturnRoute,
  GuidesPlanDriveRoute: GuidesPlanDriveRoute,
  InternalLoginRoute: InternalLoginRoute,
  PayRentalIdRoute: PayRentalIdRoute,
  RCodeRoute: RCodeRoute,
  WellKnownAcpDotjsonRoute: WellKnownAcpDotjsonRoute,
  WellKnownApiCatalogRoute: WellKnownApiCatalogRoute,
  WellKnownOauthAuthorizationServerRoute:
    WellKnownOauthAuthorizationServerRoute,
  WellKnownOauthProtectedResourceRoute: WellKnownOauthProtectedResourceRoute,
  WellKnownOpenidConfigurationRoute: WellKnownOpenidConfigurationRoute,
  WellKnownUcpRoute: WellKnownUcpRoute,
  ApiIndexRoute: ApiIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAcpCheckout_sessionsRoute: ApiAcpCheckout_sessionsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaymentResponseRoute: ApiPaymentResponseRoute,
  ApiWebhooksIpay88Route: ApiWebhooksIpay88Route,
  BookingConfirmedRentalIdRoute: BookingConfirmedRentalIdRoute,
  CheckoutConfirmedRentalIdRoute: CheckoutConfirmedRentalIdRoute,
  InternalInviteTokenRoute: InternalInviteTokenRoute,
  WellKnownAgentSkillsIndexDotjsonRoute: WellKnownAgentSkillsIndexDotjsonRoute,
  WellKnownMcpServerCardDotjsonRoute: WellKnownMcpServerCardDotjsonRoute,
  ApiV1IndexRoute: ApiV1IndexRoute,
  ApiDocumentsAgreementRentalIdRoute: ApiDocumentsAgreementRentalIdRoute,
  ApiDocumentsInvoiceRentalIdRoute: ApiDocumentsInvoiceRentalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
